spring:
  application:
    name: techbridge-user
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  output:
    ansi:
      enabled: ALWAYS
  cache:
    type: none
  jackson: # para no enviar campos con valor nulo en json
    default-property-inclusion: NON_NULL
  jpa: # evitar el error de "LazyInitializationException" de forma descontrolada
    open-in-view: false
  mail:
    host: smtp.upm.es
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        from: ${MAIL_USERNAME}
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      clients:
        issuer-uri: http://localhost:8080/api/techbridge-user
        open-api-client-id: swagger-client
        open-api-client-secret: swagger-secret
        open-api-redirect-uris:
          - http://localhost:8081/swagger-ui/oauth2-redirect.html
        spa-client-id: techbridge-spa
        spa-login-redirect-uri: http://localhost:4200/callback
        spa-silence-renew-redirect-uri: http://localhost:4200/silent-renew.html
        spa-logout-redirect-uri: http://localhost:4200
        api-client-id: internal-api-client
        api-client-secret: internal-secret

server:
  port: 8081
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    es.techbridge: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  register: ${REGISTER_URI:http://localhost:4200/register}
  activation-url: ${ACTIVATION_URL:http://localhost:8081/users/activate}
  public-base-url: ${PUBLIC_BASE_URL:http://localhost:8081}
  login-url: ${LOGIN_URL:http://localhost:4200/}
